***Using Tensorflow like Numpy***

In [ ]:
#importing the tensorflow library
import tensorflow as tf

In [ ]:
# creating a tensor
tf.constant([[1., 2., 3.],[4., 5., 6.]])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
#to get shape and dtype
t = tf.constant([[1,2,3],[4,5,6]])
print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'int32'>


In [ ]:
#indexing
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [ ]:
#""..." means "all dimensions prior to" the specified dimension.
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]], dtype=int32)>

In [ ]:
# addition
t+10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [ ]:
# root
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [ ]:
# matrix multiplication (@ ~= tf.matmul())
t@tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

***Custom Loss Functions***

In [ ]:
def hubber_fun(y_true, y_pred):
  error = y_true - y_pred
  is_small_error = tf.abs(error) < 1
  squred_loss = tf.square(error)/2
  linear_loss = tf.abs(error) - 0.5
  return tf.where(is_small_error, squred_loss, linear_loss)

In [ ]:
# model.compile(loss = hubber_fun, optimizer = 'nadam')
# model.fit(X_train, y_train)